// Enemy type definitions — shared by server and client.
// hp = base health, speed = px/s walking left.
export const ENEMY_TYPES = [
  { id: 'slime',      name: 'Slime',         hp:  20,  speed:  55 },
  { id: 'rat',        name: 'Rat',           hp:  30,  speed:  80 },
  { id: 'bat',        name: 'Bat',           hp:  25,  speed:  95 },
  { id: 'frog',       name: 'Frog',          hp:  45,  speed:  65 },
  { id: 'snake',      name: 'Snake',         hp:  40,  speed:  88 },
  { id: 'spider',     name: 'Spider',        hp:  55,  speed:  72 },
  { id: 'beetle',     name: 'Beetle',        hp:  70,  speed:  58 },
  { id: 'wolf',       name: 'Wolf',          hp:  85,  speed: 100 },
  { id: 'boar',       name: 'Boar',          hp: 110,  speed:  82 },
  { id: 'lizard',     name: 'Lizard',        hp:  75,  speed:  92 },
  { id: 'imp',        name: 'Imp',           hp:  65,  speed: 108 },
  { id: 'mushroom',   name: 'Mushroom',      hp: 100,  speed:  45 },
  { id: 'crab',       name: 'Crab',          hp: 130,  speed:  52 },
  { id: 'scorpion',   name: 'Scorpion',      hp: 120,  speed:  68 },
  { id: 'hawk',       name: 'Hawk',          hp:  80,  speed: 118 },
  { id: 'panther',    name: 'Panther',       hp: 140,  speed: 105 },
  { id: 'golem',      name: 'Golem',         hp: 210,  speed:  35 },
  { id: 'wraith',     name: 'Wraith',        hp:  90,  speed: 112 },
  { id: 'troll',      name: 'Troll',         hp: 190,  speed:  48 },
  { id: 'harpy',      name: 'Harpy',         hp: 105,  speed: 122 },
  { id: 'wyvern',     name: 'Wyvern',        hp: 160,  speed:  95 },
  { id: 'mantis',     name: 'Mantis',        hp: 125,  speed:  90 },
  { id: 'cyclops',    name: 'Cyclops',       hp: 230,  speed:  42 },
  { id: 'minotaur',   name: 'Minotaur',      hp: 260,  speed:  58 },
  { id: 'phoenix',    name: 'Phoenix',       hp: 150,  speed: 128 },
  { id: 'ghoul',      name: 'Ghoul',         hp: 170,  speed:  78 },
  { id: 'elemental',  name: 'Elemental',     hp: 210,  speed:  68 },
  { id: 'hydra',      name: 'Hydra',         hp: 290,  speed:  52 },
  { id: 'kraken',     name: 'Kraken',        hp: 310,  speed:  47 },
  { id: 'banshee',    name: 'Banshee',       hp: 135,  speed: 135 },
  { id: 'chimera',    name: 'Chimera',       hp: 230,  speed:  85 },
  { id: 'vampire',    name: 'Vampire',       hp: 185,  speed: 115 },
  { id: 'lich',       name: 'Lich',          hp: 205,  speed:  72 },
  { id: 'titan',      name: 'Titan',         hp: 360,  speed:  40 },
  { id: 'demon',      name: 'Demon',         hp: 290,  speed:  88 },
  { id: 'dragon',     name: 'Dragon',        hp: 420,  speed:  62 },
  { id: 'undead',     name: 'Undead Giant',  hp: 460,  speed:  36 },
  { id: 'void_beast', name: 'Void Beast',    hp: 390,  speed:  78 },
  { id: 'ancient',    name: 'Ancient Horror',hp: 510,  speed:  47 },
  { id: 'overlord',   name: 'Overlord',      hp: 620,  speed:  57 },
];

const TYPE_MAP = Object.fromEntries(ENEMY_TYPES.map((e) => [e.id, e]));
export function getEnemyType(id) { return TYPE_MAP[id] || ENEMY_TYPES[0]; }
